src/discord.ts
- Fixed getConnectedApp api url. [Related PR](https://bitbucket.org/comcomai/nft-server/pull-requests/34/discord-matched-only-one-app)
=> Fix get connect app api

src/auth.ts
Added APIs for managedContracts that should be performed first before the setNftMetadata call
=> Add managedContracts-related-apis

src/types.ts
This PR was made due to changes in the Transaction schema of the NFT-server.
=> change transaction value type to number

src/store.ts, src/types.ts
The useItem function has been updated with a generic type parameter T, which represents the itemType to retrieve and use. The return type of the function is determined based on the itemType. The function accepts additional arguments (...args) specific to the itemType.
Example usage:
```
useItem(...) // returns a Promise<void> | Promise<string> | Promise<NftMetadata>.
useItem<itemType.TICKET>(...) // returns a Promise<void>.
useItem<itemType.NFT_TRAIT>(...) // returns a Promise<NftMetadata>.
useItem<itemType.NFT>(...) // returns a Promise<string>.
```
cc: @ehgmsdk20
=> Add generic return for useItem

src/activity.ts, src/ainft.ts, src/ainft721.ts, src/ainftToken.ts, src/auth.ts, src/factoryBase.ts, src/nft.ts, src/types.ts
issue
- https://www.notion.so/comcom/ainft-js-getAinft721-get-45d8cd840be94ebf84cf2853359d2145?pvs=4
- https://www.notion.so/comcom/ainft-js-setNftMetadata-9c74f11dee3d42a89f2bddfc5a49098d?pvs=4
Updates
- Add setAinWalletSigner function.
- User doesn't need to know AinWalletSigner object from ain-js.
- Update `getAinft721` to `get`.
- Add logic to check that nft exists
- Update setNftMetadata.
- Remove logic for ainft and Add AinftToken with setMetadata func.
- Add sendRequestWithoutSign.
- APIs that make txBody don't need signing.
=> Set ain wallet signer & Add AinftToken class

src/ainft721Object.ts, src/ainftToken.ts, src/nft.ts, src/types.ts
- Use `ainftObject` instead of `nft`.
- Update search functions name
- `searchAssets` -> `searchNfts`
- `searchCollections` -> `searchAinftObjects`
=> Update nftId to ainftObjectId & Update some functions name

.github/workflows/pr_test.yml, .github/workflows/pr_test_when_merged.yml, package.json
- upgraded the minimum Node.js version of `ainft-js` to 16 due to the dependency on `ainize-sdk`(>=16).
- modified the Github Actions workflow(run_test) to disable 14 and enable 18.
=> Upgrade node minimum version to 16

src/ai/assistants/assistants.ts, src/types.ts, src/util.ts, test/ai/assistants/assistants.test.ts
- add get assistant method and test code.
- [TBD] currently, only the `get()` function is supported. The implementation of the `list()` function is on hold, because the need for discussion on the query options and method.
=> [ChatAI] Get Assistant

src/ai/threads/messages/message.ts, src/ai/threads/threads.ts, src/types.ts, src/util.ts, test/ai/threads/messages/messages.test.ts, test/ai/threads/threads.test.ts
- Add create `message` and test code.
- Execute `run` when message is created. ([link](https://platform.openai.com/docs/assistants/how-it-works/runs-and-run-steps))
- In AINFT, unlike OpenAI where 'message' and 'run' are separate. but I've implemented automatic run execution upon message creation for immediate assistant response messages.
- Call flow in `message.create()`: Create Message -> Create Run -> Check Run Status (polling) -> Retrieve Message list.
=> [ChatAI] Create message

.github/workflows/pr_test.yml, .github/workflows/pr_test_when_merged.yml, src/ai/chat/assistants.ts, src/ai/chat/chat.ts, src/ai/chat/messages.ts, src/ai/chat/threads.ts, src/types.ts, src/util.ts, test/ai/chat/assistants.test.ts, test/ai/chat/chat.test.ts, test/ai/chat/messages.test.ts, test/ai/chat/threads.test.ts
- Upgrade to Node 20 in Github Actions due to Node 16 support ending by 2024 spring. ([link](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20))
- Mock functions to prevent actual transactions and calls.
- During our testing workflows, which were run in parallel across two different node environments(18, 20) connected to actual blockchain and containers, I encountered continuous errors and the tests did not execute properly.
- It was challenging to separate each environment..
- So I decided to mock all the test codes to make them independent from the environment.
=> [CI] Fix broken test workflow issue

.github/workflows/docs.yml, .github/workflows/pr_test_when_merged.yml, package.json, yarn.lock
- update node version to 18 in `docs` workflow.
- related issue: https://github.com/ainft-team/ainft-js/issues/260
=> [CI] Update node version in docs workflow

src/ai/assistant.ts, src/ai/chat.ts, src/ai/message.ts, src/ai/thread.ts, src/ainft.ts, src/utils/util.ts, test/ai/assistant.test.ts, test/ai/chat.test.ts, test/ai/message.test.ts, test/ai/thread.test.ts, test/status.test.ts
- Added signer support when initializing the sdk.
```javascript
import { AinWalletSigner } from '@ainblockchain/ain-js/lib/signer/ain-wallet-signer';
const signer = new AinWalletSigner();
const ainft = new AinftJs(null, signer, { ... });
```
- Patched _ain-js_ event handler has been confirmed in the browser. (see video)
- Added await to `ain.signer.getAddress` in a browser, returned a promise.
- Disabled transaction success check, because returned only txHash not code when transaction is sent via the signer.
https://github.com/ainft-team/ainft-js/assets/122012800/3a8db7b9-a6a7-4d8f-94a1-1a0654bcc4f6
=> Add signer support

README.md, examples/ai/assistant.js, examples/ai/deposit.js, examples/ai/message.js, examples/ai/thread.js, package.json, src/ainft.ts, src/ainize.ts, test/ai/ai.test.ts, test/ai/assistant.test.ts, test/ai/message.test.ts, test/ai/thread.test.ts, yarn.lock
- add `isConnected` API.
- rename `open` -> `connect`, `close` -> `disconnect` API.
=> [feat] Add isConnected API

src/ai/assistant.ts, src/constants.ts
- increate blockchain transaction size limit: 10kb -> 100kb
=> [feat] Increase tx size limit

src/ainft721Object.ts, src/nft.ts, src/types.ts, test/constants.ts, test/nft.test.ts
- add description and metadata field to `Ainft721Object` class.
- add nft test code.
=> [feat] improve AINFT object

src/ai/ai.ts, src/ai/assistant.ts, src/ai/message.ts, src/ai/thread.ts, src/ainft721Object.ts, src/nft.ts, src/types.ts, test/ai/assistant.test.ts, test/nft.test.ts
- remove `description` field of ainft object.
- add `metric` field of assistant.
=> [feat] add assistant metric

src/ainft721Object.ts, src/nft.ts, src/types.ts
- Add missing parameters. (slug, order)
- If you want to search ainft object by `slug` in order by `creation time`:
```typescript
const { ainftObjects } = await ainft.nft.searchAinftObjects({ slug: 'test-slug', order: 'asc' });
```
=> [bugfix] add missing parameters.

src/ai/assistant.ts, src/ai/thread.ts, src/types.ts, test/ai/thread.test.ts
- modify to use list parameter in `threads.list()`.
- add objectId field to response data for `threads.list()`.
- If you want to retrieve all threads in multi object:
```ts
const threads = ainft.threads.list(["object-id-1", "object-id-2"],  null, null, { order: 'desc' })
```
=> [feat] modify to use list parameter and add object id field.

src/nft.ts
- send search requests with sign: `searchAinftObjects()`, `searchNfts()`
=> [fix] send search request without sign.

src/ai/assistant.ts, test/ai/assistant.test.ts
- modify to use list parameter in `assistants.list()`.
```ts
const threads = ainft.assistants.list(["object-id-1", "object-id-2"],  null, { order: 'asc' })
```
=> [feat] modify to use list parameter.

src/types.ts, test/ai/assistant.test.ts
- support `gpt-4o-mini` model and deprecate `gpt-3.5-turbo` model
- ref: https://platform.openai.com/docs/models/gpt-4o-mini
=> [feat] support gpt-4o-mini model and deprecate gpt-3.5-turbo.

src/ai/thread.ts, src/utils/util.ts
- convert milliseconds to seconds.
=> [bugfix] convert milliseconds to seconds.
