ainft-team/ainft-js

- package.json
- sample/index.js
- src/assets.ts
- src/index.ts
- src/status.ts
- test/status.test.ts
- Initialize AinftJs and Assets class
- update sample code
- update status.test.code
Q) Does it matter if the url is public? e.g. API_SERVER_URL
> Initialize AinftJs and Assets class

- package.json
- src/constants.ts
- src/discord.ts
- src/index.ts
- src/types.ts
- add discord class
- add signature and signatureData in ainftJs class.
> Discord class

- src/discord.ts
- src/event.ts
Apply new apis in [NFT server PR](https://bitbucket.org/comcomai/nft-server/pull-requests/25)
- getTaskTypeList
- getRewardTypeList
- getConnectedApps
> Add simple apis

- src/discord.ts
- src/types.ts
- Add getConnectedTasksWithChannel
- Add return type getConnectedApps
- Add some types
> Add getConnectedTasksWithChannel

- src/auth.ts
- src/index.ts
- src/types.ts
- getUser
- addUserEthAddress
- removeUserEthAddress
> Add Auth class and user related functions.

- src/asset.ts
- src/auth.ts
- src/discord.ts
- src/event.ts
- src/types.ts
- src/util.ts
- [400 Error (Your client has issued a malformed or illegal request) ](https://www.notion.so/comcom/400-Error-Your-client-has-issued-a-malformed-or-illegal-request-bb514f745af34ae2a1c3cc0130e010cd)
- Move signature to Authorization header.
1. When use GET or DELETE method, Are params also included in querystring? for signature?
1. Not use params, only use querystring.
2. Add params in querystring. (But will have a duplicated information)
> Move signature to Authorization header.

- src/ainftBase.ts
- src/asset.ts
- src/auth.ts
- src/discord.ts
- src/event.ts
- src/index.ts
- src/store.ts
- src/types.ts
- Add Store Class
- Add getStoreItemList, getUserInventory, getStoreItemInfo, purchaseStoreItem.
> Store V1 Features

- src/ainftBase.ts
- baseUrl defined with default value and use setBaseUrl in constructor
> fix: use setBaseUrl when constructor

- src/asset.ts
Related changes: https://bitbucket.org/comcomai/nft-server/pull-requests/70/add-get-nft-by-symbol-api-update-nft-api
Related issue: https://www.notion.so/comcom/bot-nft-80829e73a5cf4e198558d6731cd9fb5d
> Add getNftContractBySymbol, getNft, update nft api queries.

- src/event.ts
- src/types.ts
- add event.getActivity
- add event.updateActivityStatus
> Get Activity

- src/event.ts
- src/types.ts
Reverts ainft-team/ainft-js#34
- This PR will be created for develop branch.
> Revert "Get Activity"

- src/event.ts
- src/types.ts
- #34 is reverted and Re-create PR for develop branch
> Get Activity 

- src/ainftBase.ts
- src/asset.ts
- src/auth.ts
- src/discord.ts
- src/event.ts
- src/index.ts
- src/store.ts
- src/types.ts
- src/util.ts
Changes:
- Added credit related functions
- Added sendRequest function
> Added credit related functions

- src/asset.ts
Related: https://bitbucket.org/comcomai/nft-server/pull-requests/75/add-nft-symbol-get-api
> Add getAppNftSymbolList().

- src/types.ts
Accidentally left these in the code.. 😢
> Fix merge conflict marks.

- package.json
> Release/0.3.4 -> develop

- src/ainftBase.ts
- src/util.ts
As-is:
```
{
_original: {
appId: 'babyshark_dev',
userId: '...',
quantity: -1
},
details: [
{
message: '"quantity" must be a positive number',
path: [Array],
type: 'number.positive',
context: [Object]
}
]
}
```
To-be:
```
{
message: '"quantity" must be a positive number',
path: [ 'quantity' ],
type: 'number.positive',
context: { label: 'quantity', value: -1, key: 'quantity' }
}
```
> Handle joi errors.

- README.md
- package.json
- Update node engine version to 12
> update node engine requirement

- src/store.ts
- src/types.ts
Related: https://bitbucket.org/comcomai/nft-server/pull-requests/109/feature-liayoo-use-item-api
> Add useItem() function.

- src/auth.ts
- We will add whitelisting and have decided to get an accessAddress when registering for a whitelist.
> Don't generate accessAddress from accessKey

- src/store.ts
- src/types.ts
Related: https://bitbucket.org/comcomai/nft-server/pull-requests/129
> Add optional params to ItemTryOnParams.

- src/store.ts
- src/types.ts
Add item create, update, deregisterFromAllStore, registerItem, deregisterItem, updateStoreItem
> Item & Store methods

- src/ainft.ts
- src/discord.ts
- src/personaModels.ts
- src/types.ts
- Create `PersonaModels` class and add persona model create method
> Add persona model create

- src/types.ts
- Change type of get persona model
> Change get persona model type

- src/types.ts
Add DISCORD_INVITE to taskTypeCategory
> Add discord invite TaskTypeCategory

- src/store.ts
- src/types.ts
Add getItemPurchaseHistory/getUserPurchaseHistory
> Add getItemPurchaseHistory/getUserPurchaseHistory

- src/store.ts
Related: https://bitbucket.org/comcomai/nft-server/pull-requests/146
> Update useItem return type.

- src/store.ts
- src/types.ts
> Add getPurchaseHistory

- tools/create-ainft-server-app/README.md
- tools/create-ainft-server-app/create-access-key.js
- tools/create-ainft-server-app/create-ainft-server-app.js
- Add create access key script
- Update access key required
- Update readme
> Updates create-ainft-server-app tool.

- .gitignore
- README.md
- src/ainft.ts
- src/event.ts
- Add ainft and event module simple documentation.
> Docs - ainft, event

- src/personaModels.ts
- src/types.ts
> Add persona model chat

- src/discord.ts
- src/types.ts
- Add get persona models for discord server
> Add get persona models for discord server

- src/discord.ts
- src/types.ts
- Save persona model name to discord channel 
- Redefine persona model info types
> Save persona model name in channel and redefine persona model info types

- src/asset.ts
- Add addNftSymbol/removeNftSymbol
> Add addNftSymbol/removeNftSymbol

- src/discord.ts
- src/types.ts
Add parameter for ambiguous inviter case
> Add ambiguous inviters 

- src/types.ts
> fix: UpdateStoreItemParams's quantity type

- src/asset.ts
New method ( withdrawAppCredit ) added
> Add withdrawAppCredit

- src/asset.ts
- test/status.test.ts
Changes:
- add setNftMetadata
- get options when add nft symbol
[setNftMetadata result](https://console.firebase.google.com/u/0/project/nft-server-dev/database/nft-server-dev-default-rtdb/data/~2FnftMetadataHosting~2FETH-TEST~2Fgoerli~2F0xe18Daf5488f9E88fedE977452B5E0b1787cAf253~2F171~2Fmetadata)
> Add setNftMetadata

- src/asset.ts
- src/types.ts
Add new method (getWithdrawListByUserId)
> Add getWithdrawListByUserId

- src/asset.ts
Add new method lockupUserBalance
> feat: add lockupUserBalance

- src/ainft.ts
- src/textToArt.ts
- src/types.ts
> feat: add text to art

- src/store.ts
- src/types.ts
> Add JsDoc for Store module

- .github/workflows/create_release.yml
- .github/workflows/pr_test.yml
- .github/workflows/pr_test_when_merged.yml
- .github/workflows/send_slack.yml
Added github actions for release process automization
- create_release.yml: Create release branch and upgrade version with given input.
- pr_test.yml: Run test when pr is opened or ready for review.
- pr_test_when_merged.yml: Run test when pr is merged in main/develop branch. If the name of branch starts with 'release', publish package to npm registry.
- send_slack.yml: Send slack when 'pr test when merged' failed. Connect with the slack channel: #ainft-dev.
> Add github action files

- src/asset.ts
- src/types.ts
Add new method depositToken for nft-server.
> Add depositToken

- src/asset.ts
- src/auth.ts
Add new method getUserDepositAddress.
> Add getUserDepositAddress

- src/credit.ts
- src/types.ts
Add a method (getDepositHistory) and types
> add getDepositHistory

- src/types.ts
Related PRs:
- https://bitbucket.org/comcomai/nft-server-cloud-functions/pull-requests/37
- https://bitbucket.org/comcomai/nft-server/pull-requests/265
> Change metadata type

- src/types.ts
add blockNumber to write lastBlockNumber when transaction is received
> feat: add blockNumber

- src/types.ts
add name field at itemPucrhaseHistory type and itemHistory type
> feat: add name at item history

- src/nft.ts
- src/types.ts
Add methods for native nft
- createNftCollection
- mintNft
- transferNft
- searchNft
> Add create, mint, transfer, search method for native nft

- src/credit.ts
- at getDepositHistory, i deleted chain and reset api Path.
> Feat : change deposit history path

- src/personaModels.ts
- src/types.ts
- Persona model에서 소각되는 credit 정보를 알려주는 내용을 추가하였습니다.
> feat: add persona model credit info

- src/credit.ts
Add chain param for withdrawAppCredit.
> Add chain param for withdrawAppCredit

- src/types.ts
Change withdraw types to include 'chain'.
> Fix withdraw types

- src/nft.ts
- src/types.ts
Add tokenUpdatePermission to createNftCollection params.
> Update createNftCollection params

- src/auth.ts
Update createApp & initializeApp for add other app owner
> Fix create app params

- src/nft.ts
- src/types.ts
Update setNftMetadata params for support native nft.
> Update setNftMetadata params

- src/auth.ts
- src/constants.ts
Updated 3 functions according to ainftJs discussion.
> Update createApp, registerBlockchainApp, delegateApp

- README.md
- src/ainft.ts
- src/auth.ts
- src/constants.ts
- src/nft.ts
- src/types.ts
- src/util.ts
- Separate func and getTxBody func.
- Update ainftJs constructor
- Update setAccessKey -> setPrivateKey
- Update README
> getTxBody functions & Update readme

- package.json
- src/ainft.ts
Add createAccount func for user usability.
> Add createAccount static func

- package.json
- src/ainftBase.ts
- src/nft.ts
- src/types.ts
- src/util.ts
- tsconfig.json
- yarn.lock
Changes:
- upload image with buffer
- upload image with data url
- delete image
> Add image related apis

- src/auth.ts
- src/credit.ts
- src/discord.ts
- src/nft.ts
- src/personaModels.ts
> Documentation

- src/ainft721.ts
public follow methods for use dry run.
- getTxBodyForMint
- getTxBodyForTransfer
> Public getTxBodyFor methods

- src/nft.ts
- src/types.ts
Fix search response type
```
// AS-IS
{
list: [],
isFinal: boolean,
nextOffset: string
}
// TO-BE
{
nfts | ainftObjects: [],
isFinal: boolean,
cursor: string
}
```
> Fix search response type

- src/activity.ts
- src/ainft721Object.ts
- src/ainftToken.ts
- src/auth.ts
- src/credit.ts
- src/discord.ts
- src/eth.ts
- src/event.ts
- src/nft.ts
- src/types.ts
- Update jsDoc documentation.
- activity
- nft
- ainft721Object
- ainftToken
- credit
- discord
- eth
- event
- Fix `get` function in `ainft721Object`.
Please review the code you've worked on with a comment.
> Update jsDoc documentation

- tutorials/package.json
- tutorials/setMetadata.js
Fix `ainftObject.get()` to `ainftObject.getToken()`
> Update setNftMetadata script

- README.md
- package.json
- src/activity.ts
- src/ainft.ts
- src/ainft721Object.ts
- src/ainftToken.ts
- src/auth.ts
- src/credit.ts
- src/discord.ts
- src/eth.ts
- src/event.ts
- src/factoryBase.ts
- src/nft.ts
- src/personaModels.ts
- src/store.ts
- src/textToArt.ts
- src/types.ts
- test/status.test.ts
- tsconfig.json
- yarn.lock
- Update typedoc version for docs design.
- Update jsDoc in event, factory base, store, persona model, text-to-art.
- Update README.
- **_Update ainftJs constructor_**.
- I updated it because I thought there would be no problem even if it was set to default value and it makes easier to use.
Example updated document
> Update jsDoc & Update ainftJs constructor

- src/nft.ts
Update to get tx hash about creating ainft object app.
> Get tx hash about creating ainft object app

- src/nft.ts
- src/util.ts
- tutorials/createAinftObject.js
- tutorials/mintNft.js
- tutorials/setMetadata.js
- tutorials/transferNft.js
- Add try catch block to tutorial scripts.
- Add util func to check transaction is success.
> Update tutorial scripts & Add transaction util func

- tutorials/retrieve.js
- tutorials/search.js
Update ainft-js configuration in retrieve and search script.
> fix: search tutorial scripts

- src/ai/assistants/assistants.ts
- src/ai/chatAi.ts
- src/constants.ts
- src/types.ts
- src/util.ts
- test/ai/assistants/assistants.test.ts
- test/ai/chat.test.ts
- refactor create assistant method.
- add update assistant method and test code.
> [ChatAI] Update Assistant

- src/ai/assistants/assistants.ts
- src/types.ts
- test/ai/assistants/assistants.test.ts
- add delete assistant method and test code.
> [ChatAI] Delete Assistant

- src/ai/assistants/assistants.ts
- src/ai/chatAi.ts
- src/ai/threads/threads.ts
- src/types.ts
- src/util.ts
- test/ai/assistants/assistants.test.ts
- test/ai/chat.test.ts
- test/ai/threads/threads.test.ts
- add create thread method and test code.
- setup assistant for thread test.
> [ChatAI] Create thread 

- src/ai/assistants/assistants.ts
- src/ai/threads/threads.ts
- src/types.ts
- src/util.ts
- test/ai/threads/threads.test.ts
- add update thread method and test code.
> [ChatAI] Update thread

- src/ai/threads/threads.ts
- src/types.ts
- test/ai/threads/threads.test.ts
- add delete thread method and test code.
- add get thread method and test code.
> [ChatAI] Delete, Get thread

- src/ai/chat/assistants.ts
- src/ai/chat/chat.ts
- src/ai/chat/messages.ts
- src/ai/chat/threads.ts
- src/ainft721Object.ts
- src/types.ts
- src/util.ts
- test/ai/chat/assistants.test.ts
- test/ai/chat/chat.test.ts
- test/ai/chat/messages.test.ts
- test/ai/chat/threads.test.ts
- add tsdoc comments for `Chats` class.
- add tsdoc comments for `Assistants` class.
- add tsdoc comments for `Threads` class.
- add tsdoc comments for `Messages` class.
- some refactoring..
- add `sendRequestToService` function
- rename variable, function
> [docs] Add comments to core classes.

- src/ai/chat/messages.ts
- src/types.ts
- src/util.ts
- test/ai/chat/messages.test.ts
- update schema and interfaces to align with actual Ainize response format.
- resolve Ainize response format issue, completing all `message` end-to-end tests.
> Fix message format issue

- src/ainft.ts
- src/chat/assistants.ts
- src/chat/chat.ts
- src/chat/messages.ts
- src/chat/threads.ts
- test/chat/assistants.test.ts
- test/chat/chat.test.ts
- test/chat/messages.test.ts
- test/chat/threads.test.ts
- fix folder structure: src/ai/chat -> src/chat
- fix `retrieve_run` interval time: 1 sec -> 2 sec
- mock function in `message` test code (in _test/chat/messages.test.ts_)
> Mock function in message test

- examples/chat/message.js
- examples/chat/thread.js
- package.json
- src/chat/assistants.ts
- src/chat/chat.ts
- src/chat/messages.ts
- src/chat/threads.ts
- src/constants.ts
- src/types.ts
- src/util.ts
- test/chat/chat.test.ts
- rename parameter `provider` to `serviceNickname`.
- change ainize service name.
> Beta/1.1.0/9 -> Develop

- src/chat/assistants.ts
- src/chat/threads.ts
- src/types.ts
- test/assistants.test.ts
- test/chat.test.ts
- test/messages.test.ts
- test/test_data.ts
- test/threads.test.ts
- Add mock apis (assistant: `list`, `mintAndCreate`,  thread: `list`, `createAndSend`)
> [feat] Add mock apis.

- src/ai/assistant.ts
- src/ai/message.ts
- src/ai/thread.ts
- src/constants.ts
- src/types.ts
- src/utils/path.ts
- src/utils/util.ts
- src/utils/validator.ts
- test/ai/message.test.ts
- test/ai/thread.test.ts
- test/test_data.ts
- Decrease thread max siblings value.
- `THREAD_GC_MAX_SIBLINGS` = 20
- `THREAD_GC_NUM_SIBLINGS_DELETED` = 10
- Add list thread API.
- Add create and run thread API.
- Small refactoring...
> Add list, createAndRun thread API

- package.json
- yarn.lock
- Upgrade ain-js version to `1.9.0`.
- Upgrade ainize-js version to `1.1.2`.
> Upgrade ain-js, ainize-js package version

- package.json
- Release 2.1.0-beta.3 version.
- ref) https://www.npmjs.com/package/@ainft-team/ainft-js/v/2.1.0-beta.3
> chore: release 2.1.0-beta.3.

- package.json
- src/ai/assistant.ts
- src/ai/chat.ts
- src/ai/message.ts
- src/ai/thread.ts
- src/ainft.ts
- src/ainize.ts
- src/constants.ts
- src/factoryBase.ts
- src/types.ts
- src/utils/validator.ts
- test/ai/assistant.test.ts
- test/ai/chat.test.ts
- test/ai/message.test.ts
- test/status.test.ts
- test/test_data.ts
- add 'ainize' as public member variable.
- add `mint` assistant api.
- add create options for assistant. (autoName, autoProfileImage)
- allow user to `create`, `update`, `delete` assistant for whitelisted objects.
- based on closed pull request: https://github.com/ainft-team/ainft-js/pull/275
> [feat] Add assistant api for user

- src/ai/thread.ts
- src/types.ts
- test/ai/thread.test.ts
- Update create thread API
- Update list threads API (filter, cursor-based pagination)
> [feat] Update create, list thread api.

- package.json
- yarn.lock
- chore: upgrade ainize-js version to 1.2.0.
> Upgrade ainize-js version to 1.2.0.

- src/ai/assistant.ts
- src/types.ts
- add token id to list assistant response.
> [feat] Update list assistants api.

- src/ai/message.ts
- add missing param: `address`
> [fix]: add missing param.

- package.json
- src/ai/assistant.ts
- src/ai/message.ts
- src/ai/thread.ts
- src/ainft.ts
- src/types.ts
- src/utils/util.ts
- src/utils/validator.ts
- test/ai/assistant.test.ts
- test/ai/message.test.ts
- test/ai/thread.test.ts
- yarn.lock
- upgrade `@ainblockchain/ain-js` to version 1.10.1.
- add `is_shallow` option when retrieving value.
- fix query apis to read data from blockchain. (in assistant, thread, message)
Related issues:
- https://github.com/ainft-team/ainft-js/issues/284
> [bugfix] Read data from blockchain

- src/ai/message.ts
- automatically set thread title based on last message.
- fix transaction size exceeds limit error when using create message api.
> [feat] automatically set thread title.

- package.json
- yarn.lock
> [deps] update ainize-js to 1.2.1.

- src/ai/ai.ts
- src/ai/assistant.ts
- src/ai/message.ts
- src/ai/thread.ts
- src/constants.ts
- src/factoryBase.ts
- src/nft.ts
- src/utils/index.ts
- src/utils/transaction.ts
- src/utils/util.ts
- check transaction size: 10kb
- add transaction util file
> [bugfix] check transaction size

- src/types.ts
- add support for [GPT-4o](https://platform.openai.com/docs/models/gpt-4o) model.
> [feat] Add support for gpt-4o model

- src/ai/assistant.ts
- src/ai/thread.ts
- src/types.ts
- src/utils/util.ts
- test/ai/assistant.test.ts
- add owner field to assistant model.
> [feat] Add owner field to assistant model.

- src/ai/thread.ts
- add token ID to thread creation response.
> [feat] add token id to thread creation response.

- package.json
- src/ainft.ts
- yarn.lock
- Add connection and disconnection callback to `connect` function.
- https://github.com/ainft-team/ainft-js/issues/300
> [feat] Add connection callback

- src/nft.ts
- add description, metadata field to ainft object creation params.
> [feat] Add description and metadata to ainft object creation

- package.json
- src/ainft.ts
- yarn.lock
- add custom client ID when using connect() function.
> feat: add custom client id when connect().

- src/ainft.ts
- src/types.ts
- add connect params.
```ts
await ainft.connect({ "customClientId": "your-custom-client-id" });
```
> [bugfix] add connect params.

- src/nft.ts
- src/types.ts
- add `slug` to object search param.
> [feat] add slug to object search param.

- src/nft.ts
> [docs] update tsdoc comment.

- src/ai/ai.ts
- src/ai/assistant.ts
- src/ai/message.ts
- src/ainft.ts
- src/ainft721Object.ts
- src/error.ts
- src/nft.ts
- src/types.ts
- src/utils/ainize.ts
- src/utils/decorator.ts
- src/utils/env.ts
- src/utils/transaction.ts
- src/utils/util.ts
- src/utils/validator.ts
- Add `AinftError` custom error class.
- Replace error to custom error with detailed error code.
> [refactor] add ainft error class.

- src/ai/ai.ts
- src/ai/assistant.ts
- src/ai/message.ts
- src/ai/thread.ts
- src/types.ts
- add `updated` sorting for threads.
> [feat] add updated sorting for threads.

- src/ai/thread.ts
- add missing token `owner` field.
> fix: add missing owner field.

- src/types.ts
- add `Money` interface for clarity.
> [fix] add money interface.

- src/ai/assistant.ts
- src/ai/message.ts
- src/ai/thread.ts
- src/constants.ts
- src/utils/util.ts
- src/utils/validator.ts
> [bugfix] fix fetch logic.
